Repository Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2, pull requests merged in 2020-02, with the labels that each got.

#278 Handle tailing slashes in configured Authority and Instance
  Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
  Microsoft.Identity.Web/TokenAcquisition.cs
  Microsoft.Identity.Web/WebApiServiceCollectionExtensions.cs
Labels: enhancement

#235 Update MSGraphService.cs
  5-WebApp-AuthZ/5-2-Groups/Services/MicrosoftGraph-Rest/MSGraphService.cs
Labels: bug

#282 Test and fix B2C web app calls web api scenario [WIP]
  4-WebApp-your-API/Client/Program.cs
  4-WebApp-your-API/Client/Services/TodoListService.cs
  4-WebApp-your-API/Client/Startup.cs
  4-WebApp-your-API/Client/TodoListClient.csproj
  4-WebApp-your-API/TodoListService/Program.cs
  4-WebApp-your-API/TodoListService/Startup.cs
  Microsoft.Identity.Web/AuthorizeForScopesAttribute.cs
  Microsoft.Identity.Web/Base64UrlHelpers.cs
  Microsoft.Identity.Web/ClaimConstants.cs
  Microsoft.Identity.Web/ClaimsPrincipalExtensions.cs
  Microsoft.Identity.Web/ClientInfo.cs
  Microsoft.Identity.Web/Resource/AadIssuerValidator.cs
  Microsoft.Identity.Web/Resource/OpenIdConnectMiddlewareDiagnostics.cs
  Microsoft.Identity.Web/TokenAcquisition.cs
  Microsoft.Identity.Web/WebApiServiceCollectionExtensions.cs
  Microsoft.Identity.Web/WebAppServiceCollectionExtensions.cs
Labels: in progress

#295 Update to MSAL.NET 4.8.2
  .gitignore
  Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
Labels: merge after msal release
